course_name = "高等电路与电子分析"
course_code = "EE2004"
repo_type = "normal"
description = """
2024 年秋季学期自动化与电气工程集群开设的缝合课程。该课程补充讲授了《电路与电子学》课程未讲授的部分内容。该课程没有实验。

2025 秋，该课程与[《理论力学II》](https://hoa.moe/docs/sophomore-autumn/emec1002/)二选一。

要查找资料及查看学习建议，可以前往以下链接：

[电路IA](https://hoa.moe/docs/fresh-spring/ee1011a/)

[电路IB](https://hoa.moe/docs/sophomore-autumn/ee1011b/)

[模拟电子技术基础](https://hoa.moe/docs/sophomore-spring/ee1007/)

[数字电子技术基础](https://hoa.moe/docs/sophomore-spring/ee1009/)
"""

[lecturers]

[[lecturers.items]]
name = "王灿"

[[lecturers.items]]
name = "赵飞"

[[lecturers.items]]
name = "潘学伟"

[[lecturers.items]]
name = "喻锦程"

[[lecturers.items]]
name = "王毅"

[[lecturers.items]]
name = "谷雨"

[[lecturers.items]]
name = "梁亮"

[[lecturers.items]]
name = "孙丽"

[[lecturers.items]]
name = "王立欣"

[[sections]]
title = "课程内容"

[[sections.items]]
content = """
{{% details title="电路部分（32 学时）" closed="true" %}}
- 三相交流电路（6 学时）
  - 三相电路的星形和三角形联结
  - 对称三相电路计算和不对称三相电路计算
  - 三相电路功率
- 非正弦交流电路（2 学时）
  - 非正弦周期量的傅里叶分解
  - 非正弦周期电路的计算
- 频率特性和谐振现象（2 学时）
  - 网络函数和频率特性
  - 串/并联谐振电路特性和计算
- 线性电路的暂态分析（14 学时）
  - 电路量的初始值
  - 一阶电路的零输入响应、零状态响应
  - 一阶电路全响应
  - 二阶电路的暂态过程和状态变量分析法
  - 复频域电路模型和分析（6 学时）
- 二端口网络（3 学时）
  - 六种二端口网络方程参数计算
  - 二端口网络的联结和级联
- 均匀传输线（5 学时）
  - 分布式参数电路方程
  - 均匀传输线正弦稳态解
  - 无损耗线和驻波
  - 波的发出和反射，无损耗线行波分析  
{{% /details %}}

{{% details title="模电部分（16 学时）" closed="true" %}}
- 运算放大器的基本应用电路（6 学时）
  - 共射基本放大电路的组成及工作原理
  - 基本放大电路的分析方法
    - 静态工作点计算
    - 交直流负载线，图解法
    - 低频小信号模型和等效电路分析
  - 共射基本放大电路和共集基本放大电路
- 集成运算放大电路（6 学时）
  - 多级放大电路概述：耦合方式、放大倍数计算、输入输出阻抗
  - 差分放大电路的组成、差模、共模分析方法
  - 电流源电路分析
  - 互补输出级电路分析
- 直流电源（4 学时）
  - 直流稳压电源的组成
  - 单相半波、全波整流电路的结构、原理和性能指标
  - 滤波电路的结构、原理和性能指标
  - 串联型稳压电路的结构和工作原理
  - 三端集成稳压器的类型和典型应用电路
{{% /details %}}

{{% details title="数电部分（16 学时）" closed="true" %}}
- 门电路（6 学时）
  - 二极管门电路
  - CMOS 门电路
  - TTL 门电路
- 脉冲波形的产生和整形电路（6 学时）
  - 施密特触发电路
  - 555 定时器的工作原理与应用
  - 555 定时器构建单稳态电路、多谐振荡电路的方法及参数分析方法
- 加法器（2 学时）
  - 串行加法器的分析与设计方法，集成 4 位加法器 74LS283
- 存储器（2 学时）
  - 存储器（SRAM, ROM）的结构与功能
  - 存储器的位拓展方式和字拓展方式
  - 利用存储器实现组合逻辑函数的方法

{{% /details %}}
"""

[[sections]]
title = "关于考试"

[[sections.items]]
content = "2024 年秋季学期的期末考试题型为 8 题填空 + 8 题计算，其中填空题和计算题均为 4 题电路 + 2 题模电 + 2题数电。和电路与电子学一样，电路部分计算量较大，模电和数电部分基本是课后题改编和概念性问答。"
author = { name = "Gaster", link = "https://github.com/WDGaster703", date = "2025-01" }

